name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  Release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependancies
        run: make install

      - name: Run Python test suite
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          make test

      - name: Run build
        run: |
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
